session_name: DBG-NETWORK
start_directory: ~/
suppress_history: false        
windows:
  - window_name: traffic
    window_index: 1
    layout: main-horizontal
    options:
      main-pane-height: 10
    panes:
      - shell_command: ifconfig
      - shell_command: iftop \
      - shell_command: ifconfig \
      - shell_command: nicstat 30 \
  - window_name: port
    window_index: 2
    panes:
      - shell_command: lsof -i :<port> -p \
      - shell_command: netstat -tulnap | grep <port> \
  - window_name: DNS
    window_index: 3
    panes:
      - shell_command: dig www.google.com \
  - window_name: Realtime Traceroute
    window_index: 4
    panes:
      - shell_command: mtr www.google.com \
  - window_name: SS
    window_index: 5
    panes:
      - shell_command: ss -ta | less \
  - window_name: ARP
    window_index: 6
    panes:
      - shell_command: arp -n \
  - window_name: tcpdump
    window_index: 7
    panes:
      - shell_command: tcpdump -i <nic> port <port> src <ip> dst <ip> \
