session_name: DBG-IO
start_directory: ~/
suppress_history: false        
windows:
  - window_name: cpu
    window_index: 2
    layout: main-horizontal
    options:
      main-pane-height: 20
    panes:
      - shell_command: mpstat -P ALL
      - shell_command: lscpu
      - shell_command: cpustat \
      - shell_command: dmidecode -t 17
  - window_name: io
    window_index: 4
    panes:
      - shell_command: iostat -xk 30
      - shell_command: iotop
  - window_name: disk
    window_index: 9
    panes:
      - shell_command: df /
      - shell_command: du \
