session_name: Poc-Java-Perf
start_directory: /data/dev/git/workspace_mcfongtw/StudyNotesOnJavaPerformance/examples/root/
suppress_history: false        
windows:
  - window_name: Base
    start_directory: /data/dev/git/workspace_mcfongtw/StudyNotesOnJavaPerformance/examples/root/perf-container-base-builder/
    window_index: 1
    focus: true
    panes:
      - shell_command: vim \
      - shell_command: vagrant destroy; vagrant up; rm package.box; vagrant package\
  - window_name: platform
    start_directory: /data/dev/git/workspace_mcfongtw/phusion_perf_platform
    window_index: 2
    panes:
      - shell_command: vim \
      - shell_command: vagrant up --provider=docker; vagrant ssh \
  - window_name: openjdk
    start_directory: /data/dev/git/workspace_mcfongtw/phusion_perf_openjdk 
    window_index: 3
    panes:
      - shell_command: vim \
      - shell_command: vagrant up --provider=docker; vagrant ssh \
  - window_name: poc
    start_directory: /data/dev/git/workspace_mcfongtw/StudyNotesOnJavaPerformance/examples/root/poc/
    window_index: 4
    panes:
      - shell_command: vim \
      - shell_command: vagrant destroy --no-parallel; vagrant up --provider=docker --no-parallel \
  - window_name: monitor
    window_index: 5
    start_directory: /data/dev/git/workspace_mcfongtw/phusion_perf_monitor_db
    panes:
      - shell_command: vim Dockerfile \
      - start_directory: /data/dev/git/workspace_mcfongtw/phusion_perf_monitor_web
        shell_command: vim Dockerfile \
  - window_name: Git
    window_index: 7
    panes:
      - shell_command: git status
  - window_name: docker
    window_index: 8
    panes:
      - shell_command: docker ps -a
      - shell_command: docker image ls
  - window_name: tmuxp
    start_directory: /data/dev/conf/tmux/tmuxp/yaml
    window_index: 9
    panes:
      - shell_command: vim dev.poc.java_perf.yml \
      - shell_command: 
