- name: "{{ ansible_distribution }} | Make sure the prereq packages are installed"
  apt:
    pkg: "{{item}}"
    state: present
  with_items: "{{ prereq_packages }}"
  become: yes
  tags:
    - installation
    - upgrade

- name: "{{ ansible_distribution }} | Install grafana package via deb url"
  apt:
    deb: "{{target_url}}"
  become: yes
  tags:
    - installation
    - upgrade

- name: " {{ ansible_distribution }} | Start and enable grafana"
  service:
    name: grafana-server
    state: started
    enabled: yes
  become: yes 
  tags:
    - installation
    - service-started
    - service-enabled

