- name: "{{ ansible_distribution }} | Make sure the magnum-opus packages are installed"
  apt:
    pkg: "{{item}}"
    state: present
  with_items: "{{ target_packages }}"
  become: yes
  tags:
    - installation
    - upgrade
