# file: filebeat/defaults/debian-armv7l.yml

---
filebeat_version: 6.x
filebeat_create_config: true

filebeat_prospectors:
  - input_type: log
    paths:
      - "/var/log/*.log"

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "localhost:9200"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "localhost:5044"

filebeat_enable_logging: false
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "false"

elasticsearch_gpg_key: '46095ACC8548582C1A2699A9D27D666CD88E42B4'

mkconfig_repo: {src: 'http://192.168.2.102:10081/OSS/MkConfig.git', dest: '/data/tools/filebeat/MkConfig', tag: 'origin/0.1.x-master'}
