- name: " {{ ansible_distribution }} | Make sure the vagrant packages are installed"
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{ target_packages }}"
  become: yes
  tags:
    - installation
    - upgrade
