- name: "{{ ansible_distribution }} | Make sure the prereq packages are installed"
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{ prereq_packages }}"
  become: yes 
  tags:
    - installation
    - upgrade

- name: " {{ ansible_distribution }} | Install sdkman under /home/{{username}}/.sdkman"
  shell: "curl -s 'https://get.sdkman.io' | bash"
  tags:
    - installation
    - upgrade

- name: " {{ ansible_distribution }} | Install multiple java packages with sdkman"
  # This will read your bash profile file, which would setup sdkman-init.sh.
  shell: "source /home/{{ username }}//.sdkman/bin/sdkman-init.sh && sdk install {{ item }}"
  args:
    executable: /bin/bash  
  with_items: "{{ sdkman_packages }}"
  tags:
    - installation
    - upgrade

- name: " {{ ansible_distribution }} | Set global variable global_check_sdkman_installed"
  set_fact: 
    global_check_sdkman_installed: true
  tags:
    - installation
    - upgrade
    - configuration
