---
- name: "{{ ansible_distribution }} | Add grafana repository via yum"
  shell: cat <<EOF | sudo tee /etc/yum.repos.d/influxdb.repo
EOF
  tags:
    - installation

- name: "{{ ansible_distribution }} | Make sure grafana packages are installed"
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{ target_packages }}"
  become: yes
  tags:
    - installation
    - upgrade

- name: " {{ ansible_distribution }} | Start influxDB"
  service:
    name: grafana-server
    state: started
    enabled: yes
  become: yes 
  tags:
    - installation
    - service-started
    - service-enabled

