- name: Create repair cron job entry
  cron: 
    name: "nodetool repair" 
    user: "{{ username }}" 
    weekday: "{{ repair_weekday }}" 
    minute: "{{ repair_start_minute | default('0') }}"
    hour: "{{ repair_start_hour | default('3') }}"
    job: "/usr/bin/nodetool repair -pr >> ~/cron.log 2>&1"
    state: present
    disabled: no

