- name: "{{ ansible_distribution }} | Install dbg_Sym_packages package via apt"
  apt:
    pkg: "{{item}}"
    state: present
  with_items: "{{ dbg_sym_packages }}"
  become: yes 
  tags:
    - installation
    - upgrade

