- name: " {{ ansible_distribution }}  | Make sure the linux-kernel packages are installed"
  apt:
    pkg: "{{item}}"
    state: present
  with_items: "{{ target_packages }}"
  become: yes
  tags:
    - installation
    - upgrade

- name: " {{ ansible_distribution }} | include: debian/debug-symbol.yml"
  include: debian/debug-symbol.yml
  when: enable_debug_symbol and dbg_sym_packages

