- name: " {{ ansible_distribution }} | Make sure the ntp packages are installed"
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{ target_packages }}"
  become: yes
  tags:
    - installation
    - upgrade

- name: " {{ ansible_distribution }} | Copy /etc/ntp.conf"
  copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    mode: "u=rw,g=r,o=r"
  become: yes 
  tags:
    - installation
    - configuration

- name: " {{ ansible_distribution }} | start and enable NTP"
  service:
    name: ntpd
    state: started
    enabled: yes
  become: yes 
  tags:
    - installation
    - service-started
    - service-enabled
          
