- name: "{{ ansible_distribution }} | Make sure the vim packages are installed"
  yum:
    pkg: "{{item}}"
    state: present
  with_items: "{{ target_packages }}"
  become: yes
  tags:
    - installation
    - upgrade

