- name: "{{ ansible_distribution }} | swap - remove current swaps from fstab"
  lineinfile:
    dest: /etc/fstab
    regexp: '^[^#].*swap.*'
    state: absent
    backup: yes
  become: yes
  when: disable_swap is defined and disable_swap == true
  tags:
    - installation

- name: "{{ ansible_distribution }} | swap - disable swap"
  command: swapoff --all
  #ignore_errors: yes
  become: yes
  when: disable_swap is defined and disable_swap == true
  tags:
    - installation
